from django import forms
from gandi.models import Dominio, countries
from mezzanine.pages.models import Page
from django.contrib import admin
from mezzanine.pages.admin import PageAdmin
from datetimewidget.widgets import DateTimeWidget
from datetime import date

LIST = (
('za.com', 'za.com'),
('za', 'za'),
('yt', 'yt'),
('tf', 'tf'),
('so', 'so'),
('re', 're'),
('mu', 'mu'),
('mg', 'mg'),
('cm', 'cm'),
('xn--p1ai', 'xn--p1ai'),
('vc', 'vc'),
('uk.net', 'uk.net'),
('uk.com', 'uk.com'),
('uk', 'uk'),
('se.net', 'se.net'),
('se.com', 'se.com'),
('se','se'),
('se', 'se'),
('ru.com', 'ru.com'),
('ru', 'ru'),
('ro', 'ro'),
('pt', 'pt'),
('pl', 'pl'),
('org.uk', 'org.uk'),
('nu', 'nu'),
('no.com', 'no.com'),
('no.com','no.com'),
('no', 'no'),
('nl', 'nl'),
('me.uk', 'me.uk'),
('me', 'me'),
('lv', 'lv'),
('lu', 'lu'),
('lt', 'lt'),
('li', 'li'),
('je', 'je'),
('it', 'it'),
('im', 'im'),
('hu.net', 'hu.net'),
('hu.com', 'hu.com'),
('gr.com', 'gr.com'),
('gr', 'gr'),
('gg', 'gg'),
('gd', 'gd'),
('gb.net', 'gb.net'),
('gb.com', 'gb.com'),
('fr', 'fr'),
('fi', 'fi'),
('eu.com', 'eu.com'),
('eu', 'eu'),
('es', 'es'),
('dk', 'dk'),
('de.com', 'de.com'),
('de', 'de'),
('com.de', 'com.de'),
('co.uk', 'co.uk'),
('ch', 'ch'),
('cat', 'cat'),
('be', 'be'),
('at', 'at'),
('xn--fiqs8s', 'xn--fiqs8s'),
('ws', 'ws'),
('wf', 'wf'),
('tw', 'tw'),
('tv', 'tv'),
('tl', 'tl'),
('sc', 'sc'),
('sb', 'sb'),
('sa.com', 'sa.com'),
('pw', 'pw'),
('ph', 'ph'),
('nz', 'nz'),
('nf', 'nf'),
('mn', 'mn'),
('kr.com', 'kr.com'),
('ki', 'ki'),
('jpn.com', 'jpn.com'),
('jp.net', 'jp.net'),
('jp', 'jp'),
('io', 'io'),
('in.net', 'in.net'),
('in', 'in'),
('hk', 'hk'),
('fm', 'fm'),
('cx', 'cx'),
('cn.com', 'cn.com'),
('cn', 'cn'),
('asia', 'asia'),
('am', 'am'),
('af', 'af'),
('ae.org', 'ae.org'),
('vg', 'vg'),
('uy.com', 'uy.com'),
('us.org', 'us.org'),
('us.com', 'us.com'),
('us', 'us'),
('tc', 'tc'),
('sx', 'sx'),
('qc.com', 'qc.com'),
('pm', 'pm'),
('pe', 'pe'),
('mx', 'mx'),
('ms', 'ms'),
('lc', 'lc'),
('la', 'la'),
('ht', 'ht'),
('hn', 'hn'),
('gy', 'gy'),
('gs', 'gs'),
('co', 'co'),
('cc', 'cc'),
('ca', 'ca'),
('bz', 'bz'),
('br.com', 'br.com'),
('ar.com', 'ar.com'),
('ag', 'ag'),
('zone', 'zone'),
('yokohama', 'yokohama'),
('yoga', 'yoga'),
('xyz', 'xyz'),
('xxx', 'xxx'),
('xn--q9jyb4c', 'xn--q9jyb4c'),
('xn--nqv7f', 'xn--nqv7f'),
('xn--ngbc5azd', 'xn--ngbc5azd'),
('xn--mgbab2bd', 'xn--mgbab2bd'),
('xn--i1b6b1a6a2e', 'xn--i1b6b1a6a2e'),
('xn--fiq228c5hs', 'xn--fiq228c5hs'),
('xn--c1avg', 'xn--c1avg'),
('xn--80aswg', 'xn--80aswg'),
('xn--80asehdb', 'xn--80asehdb'),
('xn--6frz82g', 'xn--6frz82g'),
('xn--3ds443g', 'xn--3ds443g'),
('wtf', 'wtf'),
('world', 'world'),
('works', 'works'),
('work', 'work'),
('win', 'win'),
('wiki', 'wiki'),
('wien', 'wien'),
('whoswho', 'whoswho'),
('wedding', 'wedding'),
('website', 'website'),
('webcam', 'webcam'),
('watch', 'watch'),
('wales', 'wales'),
('voyage', 'voyage'),
('voto', 'voto'),
('voting', 'voting'),
('vote', 'vote'),
('vodka', 'vodka'),
('vlaanderen', 'vlaanderen'),
('vision', 'vision'),
('villas', 'villas'),
('video', 'video'),
('viajes', 'viajes'),
('vet', 'vet'),
('ventures', 'ventures'),
('vegas', 'vegas'),
('vacations', 'vacations'),
('uno', 'uno'),
('university', 'university'),
('travel', 'travel'),
('training', 'training'),
('trade', 'trade'),
('toys', 'toys'),
('town', 'town'),
('tours', 'tours'),
('top', 'top'),
('tools', 'tools'),
('tokyo', 'tokyo'),
('today', 'today'),
('tirol', 'tirol'),
('tires', 'tires'),
('tips', 'tips'),
('tienda', 'tienda'),
('tickets', 'tickets'),
('theater', 'theater'),
('tennis', 'tennis'),
('tel', 'tel'),
('technology', 'technology'),
('tech', 'tech'),
('team', 'team'),
('taxi', 'taxi'),
('tax', 'tax'),
('tattoo', 'tattoo'),
('taipei', 'taipei'),
('systems', 'systems'),
('sydney', 'sydney'),
('surgery', 'surgery'),
('surf', 'surf'),
('support', 'support'),
('supply', 'supply'),
('supplies', 'supplies'),
('sucks', 'sucks'),
('style', 'style'),
('study', 'study'),
('studio', 'studio'),
('space', 'space'),
('soy', 'soy'),
('solutions', 'solutions'),
('solar', 'solar'),
('software', 'software'),
('social', 'social'),
('soccer', 'soccer'),
('ski', 'ski'),
('site', 'site'),
('singles', 'singles'),
('show', 'show'),
('shoes', 'shoes'),
('shiksha', 'shiksha'),
('sexy', 'sexy'),
('sex', 'sex'),
('services', 'services'),
('scot', 'scot'),
('science', 'science'),
('schule', 'schule'),
('school', 'school'),
('sarl', 'sarl'),
('sale', 'sale'),
('saarland', 'saarland'),
('run', 'run'),
('ruhr', 'ruhr'),
('rodeo', 'rodeo'),
('rocks', 'rocks'),
('rip', 'rip'),
('rich', 'rich'),
('reviews', 'reviews'),
('review', 'review'),
('restaurant', 'restaurant'),
('rest', 'rest'),
('republican', 'republican'),
('report', 'report'),
('repair', 'repair'),
('rentals', 'rentals'),
('rent', 'rent'),
('reisen', 'reisen'),
('reise', 'reise'),
('rehab', 'rehab'),
('red', 'red'),
('recipes', 'recipes'),
('racing', 'racing'),
('quebec', 'quebec'),
('qpon', 'qpon'),
('pub', 'pub'),
('property', 'property'),
('properties', 'properties'),
('productions', 'productions'),
('pro', 'pro'),
('press', 'press'),
('porn', 'porn'),
('poker', 'poker'),
('plus', 'plus'),
('plumbing', 'plumbing'),
('place', 'place'),
('pizza', 'pizza'),
('pink', 'pink'),
('pictures', 'pictures'),
('pics', 'pics'),
('photos', 'photos'),
('photography', 'photography'),
('photo', 'photo'),
('party', 'party'),
('parts', 'parts'),
('partners', 'partners'),
('paris', 'paris'),
('osaka', 'osaka'),
('org', 'org'),
('online', 'online'),
('onl', 'onl'),
('ong', 'ong'),
('one', 'one'),
('nyc', 'nyc'),
('nrw', 'nrw'),
('ninja', 'ninja'),
('ngo', 'ngo'),
('news', 'news'),
('network', 'network'),
('net', 'net'),
('navy', 'navy'),
('name', 'name'),
('nagoya', 'nagoya'),
('movie', 'movie'),
('mortgage', 'mortgage'),
('money', 'money'),
('moe', 'moe'),
('moda', 'moda'),
('mobi', 'mobi'),
('miami', 'miami'),
('menu', 'menu'),
('men', 'men'),
('memorial', 'memorial'),
('melbourne', 'melbourne'),
('media', 'media'),
('mba', 'mba'),
('markets', 'markets'),
('marketing', 'marketing'),
('market', 'market'),
('management', 'management'),
('maison', 'maison'),
('luxury', 'luxury'),
('ltda', 'ltda'),
('love', 'love'),
('london', 'london'),
('lol', 'lol'),
('loans', 'loans'),
('loan', 'loan'),
('live', 'live'),
('link', 'link'),
('limo', 'limo'),
('limited', 'limited'),
('lighting', 'lighting'),
('life', 'life'),
('lgbt', 'lgbt'),
('legal', 'legal'),
('lease', 'lease'),
('lawyer', 'lawyer'),
('law', 'law'),
('lat', 'lat'),
('land', 'land'),
('koeln', 'koeln'),
('kiwi', 'kiwi'),
('kitchen', 'kitchen'),
('kim', 'kim'),
('kaufen', 'kaufen'),
('juegos', 'juegos'),
('joburg', 'joburg'),
('jewelry', 'jewelry'),
('jetzt', 'jetzt'),
('irish', 'irish'),
('investments', 'investments'),
('international', 'international'),
('insure', 'insure'),
('institute', 'institute'),
('ink', 'ink'),
('info', 'info'),
('industries', 'industries'),
('immobilien', 'immobilien'),
('immo', 'immo'),
('how', 'how'),
('house', 'house'),
('hosting', 'hosting'),
('host', 'host'),
('horse', 'horse'),
('holiday', 'holiday'),
('holdings', 'holdings'),
('hockey', 'hockey'),
('hiv', 'hiv'),
('hiphop', 'hiphop'),
('help', 'help'),
('healthcare', 'healthcare'),
('haus', 'haus'),
('hamburg', 'hamburg'),
('guru', 'guru'),
('guitars', 'guitars'),
('guide', 'guide'),
('gripe', 'gripe'),
('green', 'green'),
('gratis', 'gratis'),
('graphics', 'graphics'),
('golf', 'golf'),
('gold', 'gold'),
('global', 'global'),
('glass', 'glass'),
('gives', 'gives'),
('gifts', 'gifts'),
('gift', 'gift'),
('gent', 'gent'),
('garden', 'garden'),
('game', 'game'),
('gallery', 'gallery'),
('gal', 'gal'),
('fyi', 'fyi'),
('futbol', 'futbol'),
('furniture', 'furniture'),
('fund', 'fund'),
('foundation', 'foundation'),
('forsale', 'forsale'),
('football', 'football'),
('flowers', 'flowers'),
('florist', 'florist'),
('flights', 'flights'),
('fitness', 'fitness'),
('fit', 'fit'),
('fishing', 'fishing'),
('fish', 'fish'),
('financial', 'financial'),
('finance', 'finance'),
('film', 'film'),
('fashion', 'fashion'),
('farm', 'farm'),
('fans', 'fans'),
('faith', 'faith'),
('fail', 'fail'),
('express', 'express'),
('exposed', 'exposed'),
('expert', 'expert'),
('exchange', 'exchange'),
('events', 'events'),
('eus', 'eus'),
('estate', 'estate'),
('equipment', 'equipment'),
('enterprises', 'enterprises'),
('engineering', 'engineering'),
('engineer', 'engineer'),
('energy', 'energy'),
('email', 'email'),
('education', 'education'),
('durban', 'durban'),
('download', 'download'),
('domains', 'domains'),
('dog', 'dog'),
('discount', 'discount'),
('directory', 'directory'),
('direct', 'direct'),
('digital', 'digital'),
('diet', 'diet'),
('diamonds', 'diamonds'),
('design', 'design'),
('desi', 'desi'),
('dentist', 'dentist'),
('dental', 'dental'),
('democrat', 'democrat'),
('delivery', 'delivery'),
('degree', 'degree'),
('deals', 'deals'),
('dating', 'dating'),
('date', 'date'),
('dance', 'dance'),
('cymru', 'cymru'),
('cruises', 'cruises'),
('cricket', 'cricket'),
('creditcard', 'creditcard'),
('credit', 'credit'),
('courses', 'courses'),
('coupons', 'coupons'),
('country', 'country'),
('corsica', 'corsica'),
('coop', 'coop'),
('cool', 'cool'),
('cooking', 'cooking'),
('contractors', 'contractors'),
('consulting', 'consulting'),
('construction', 'construction'),
('condos', 'condos'),
('computer', 'computer'),
('company', 'company'),
('community', 'community'),
('com', 'com'),
('cologne', 'cologne'),
('college', 'college'),
('coffee', 'coffee'),
('codes', 'codes'),
('coach', 'coach'),
('co.com', 'co.com'),
('club', 'club'),
('clothing', 'clothing'),
('clinic', 'clinic'),
('click', 'click'),
('cleaning', 'cleaning'),
('claims', 'claims'),
('city', 'city'),
('church', 'church'),
('christmas', 'christmas'),
('cheap', 'cheap'),
('chat', 'chat'),
('ceo', 'ceo'),
('center', 'center'),
('catering', 'catering'),
('casino', 'casino'),
('cash', 'cash'),
('casa', 'casa'),
('careers', 'careers'),
('career', 'career'),
('care', 'care'),
('cards', 'cards'),
('capital', 'capital'),
('capetown', 'capetown'),
('camp', 'camp'),
('camera', 'camera'),
('cafe', 'cafe'),
('cab', 'cab'),
('bzh', 'bzh'),
('buzz', 'buzz'),
('business', 'business'),
('builders', 'builders'),
('build', 'build'),
('brussels', 'brussels'),
('boutique', 'boutique'),
('blue', 'blue'),
('blackfriday', 'blackfriday'),
('black', 'black'),
('biz', 'biz'),
('bio', 'bio'),
('bingo', 'bingo'),
('bike', 'bike'),
('bid', 'bid'),
('best', 'best'),
('berlin', 'berlin'),
('beer', 'beer'),
('bayern', 'bayern'),
('bargains', 'bargains'),
('bar', 'bar'),
('band', 'band'),
('audio', 'audio'),
('auction', 'auction'),
('attorney', 'attorney'),
('associates', 'associates'),
('army', 'army'),
('archi', 'archi'),
('apartments', 'apartments'),
('amsterdam', 'amsterdam'),
('alsace', 'alsace'),
('airforce', 'airforce'),
('agency', 'agency'),
('aero', 'aero'),
('adult', 'adult'),
('actor', 'actor'),
('accountants', 'accountants'),
('accountant', 'accountant'),
('academy', 'academy'),
('abogado', 'abogado'),
)

SMALL_LIST = (
('com', 'com'),
('org', 'org'),
('es', 'es'),
('info', 'info'),
('ong', 'ong'),
('pe', 'pe'),
)

TYPE_OF_USERS = (
	('0', 'Clientes Privados'),
	('1', 'Empresas'),
	('2', 'Asociasiones'),
	('3', 'Instituciones Publicas'),
)

SERVICES = (
('domain', 'Dominios'),
('gandimail', 'Correos'),
('hosting', 'Hosting'),
('iaas', 'IaaS'),
('paas', 'PaaS'),
)

CURRENCY = (
('USD', 'Dolar'),
('EUR', 'Euros'),
('GBP', 'Libras Inglesas'),
('CHF', 'Franco Suizo'),
)

COUNTRIES = (
('AD','Andorra'),
('AE','United Arab Emirates'),
('AF','Afghanistan'),
('AG','Antigua and/or Barbuda'),
('AI','Anguilla'),
('AL','Albania'),
('AM','Armenia'),
('AN','Netherlands Antilles'),
('AO','Angola'),
('AQ','Antarctica'),
('AR','Argentina'),
('AT','Austria'),
('AU','Australia'),
('AW','Aruba'),
('AZ','Azerbaijan'),
('BA','Bosnia and Herzegovina'),
('BB','Barbados'),
('BD','Bangladesh'),
('BE','Belgium'),
('BF','Burkina Faso'),
('BG','Bulgaria'),
('BH','Bahrain'),
('BI','Burundi'),
('BJ','Benin'),
('BM','Bermuda'),
('BN','Brunei Darussalam'),
('BO','Bolivia'),
('BR','Brazil'),
('BS','Bahamas'),
('BT','Bhutan'),
('BV','Bouvet Island'),
('BW','Botswana'),
('BY','Belarus'),
('BZ','Belize'),
('CA','Canada'),
('CC','Cocos (Keeling) Islands'),
('CF','Central African Republic'),
('CG','Congo'),
('CH','Switzerland'),
('CI','Ivory Coast'),
('CK','Cook Islands'),
('CL','Chile'),
('CM','Cameroon'),
('CN','China'),
('CO','Colombia'),
('CR','Costa Rica'),
('CU','Cuba'),
('CV','Cape Verde'),
('CX','Christmas Island'),
('CY','Cyprus'),
('CZ','Czech Republic'),
('DE','Germany'),
('DJ','Djibouti'),
('DK','Denmark'),
('DM','Dominica'),
('DO','Dominican Republic'),
('DS','American Samoa'),
('DZ','Algeria'),
('EC','Ecuador'),
('EE','Estonia'),
('EG','Egypt'),
('EH','Western Sahara'),
('ER','Eritrea'),
('ES','Spain'),
('ET','Ethiopia'),
('FI','Finland'),
('FJ','Fiji'),
('FK','Falkland Islands (Malvinas)'),
('FM','Micronesia, Federated States of'),
('FO','Faroe Islands'),
('FR','France'),
('FX','France, Metropolitan'),
('GA','Gabon'),
('GB','United Kingdom'),
('GD','Grenada'),
('GE','Georgia'),
('GF','French Guiana'),
('GH','Ghana'),
('GI','Gibraltar'),
('GK','Guernsey'),
('GL','Greenland'),
('GM','Gambia'),
('GN','Guinea'),
('GP','Guadeloupe'),
('GQ','Equatorial Guinea'),
('GR','Greece'),
('GS','South Georgia South Sandwich Islands'),
('GT','Guatemala'),
('GU','Guam'),
('GW','Guinea-Bissau'),
('GY','Guyana'),
('HK','Hong Kong'),
('HM','Heard and Mc Donald Islands'),
('HN','Honduras'),
('HR','Croatia (Hrvatska)'),
('HT','Haiti'),
('HU','Hungary'),
('ID','Indonesia'),
('IE','Ireland'),
('IL','Israel'),
('IM','Isle of Man'),
('IN','India'),
('IO','British Indian Ocean Territory'),
('IQ','Iraq'),
('IR','Iran (Islamic Republic of)'),
('IS','Iceland'),
('IT','Italy'),
('JE','Jersey'),
('JM','Jamaica'),
('JO','Jordan'),
('JP','Japan'),
('KE','Kenya'),
('KG','Kyrgyzstan'),
('KH','Cambodia'),
('KI','Kiribati'),
('KM','Comoros'),
('KN','Saint Kitts and Nevis'),
('KP','Korea, Democratic Peoples Republic of'),
('KR','Korea, Republic of'),
('KW','Kuwait'),
('KY','Cayman Islands'),
('KZ','Kazakhstan'),
('LA','Lao Peoples Democratic Republic'),
('LB','Lebanon'),
('LC','Saint Lucia'),
('LI','Liechtenstein'),
('LK','Sri Lanka'),
('LR','Liberia'),
('LS','Lesotho'),
('LT','Lithuania'),
('LU','Luxembourg'),
('LV','Latvia'),
('LY','Libyan Arab Jamahiriya'),
('MA','Morocco'),
('MC','Monaco'),
('MD','Moldova, Republic of'),
('ME','Montenegro'),
('MG','Madagascar'),
('MH','Marshall Islands'),
('MK','Macedonia'),
('ML','Mali'),
('MM','Myanmar'),
('MN','Mongolia'),
('MO','Macau'),
('MP','Northern Mariana Islands'),
('MQ','Martinique'),
('MR','Mauritania'),
('MS','Montserrat'),
('MT','Malta'),
('MU','Mauritius'),
('MV','Maldives'),
('MW','Malawi'),
('MX','Mexico'),
('MY','Malaysia'),
('MZ','Mozambique'),
('NA','Namibia'),
('NC','New Caledonia'),
('NE','Niger'),
('NF','Norfolk Island'),
('NG','Nigeria'),
('NI','Nicaragua'),
('NL','Netherlands'),
('NO','Norway'),
('NP','Nepal'),
('NR','Nauru'),
('NU','Niue'),
('NZ','New Zealand'),
('OM','Oman'),
('PA','Panama'),
('PE','Peru'),
('PF','French Polynesia'),
('PG','Papua New Guinea'),
('PH','Philippines'),
('PK','Pakistan'),
('PL','Poland'),
('PM','St. Pierre and Miquelon'),
('PN','Pitcairn'),
('PR','Puerto Rico'),
('PS','Palestine'),
('PT','Portugal'),
('PW','Palau'),
('PY','Paraguay'),
('QA','Qatar'),
('RE','Reunion'),
('RO','Romania'),
('RS','Serbia'),
('RU','Russian Federation'),
('RW','Rwanda'),
('SA','Saudi Arabia'),
('SB','Solomon Islands'),
('SC','Seychelles'),
('SD','Sudan'),
('SE','Sweden'),
('SG','Singapore'),
('SH','St. Helena'),
('SI','Slovenia'),
('SJ','Svalbard and Jan Mayen Islands'),
('SK','Slovakia'),
('SL','Sierra Leone'),
('SM','San Marino'),
('SN','Senegal'),
('SO','Somalia'),
('SR','Suriname'),
('ST','Sao Tome and Principe'),
('SV','El Salvador'),
('SY','Syrian Arab Republic'),
('SZ','Swaziland'),
('TC','Turks and Caicos Islands'),
('TD','Chad'),
('TF','French Southern Territories'),
('TG','Togo'),
('TH','Thailand'),
('TJ','Tajikistan'),
('TK','Tokelau'),
('TM','Turkmenistan'),
('TN','Tunisia'),
('TO','Tonga'),
('TP','East Timor'),
('TR','Turkey'),
('TT','Trinidad and Tobago'),
('TV','Tuvalu'),
('TW','Taiwan'),
('TY','Mayotte'),
('TZ','Tanzania, United Republic of'),
('UA','Ukraine'),
('UG','Uganda'),
('UM','United States minor outlying islands'),
('US','United States'),
('UY','Uruguay'),
('UZ','Uzbekistan'),
('VA','Vatican City State'),
('VC','Saint Vincent and the Grenadines'),
('VE','Venezuela'),
('VG','Virgin Islands (British)'),
('VI','Virgin Islands (U.S.)'),
('VN','Vietnam'),
('VU','Vanuatu'),
('WF','Wallis and Futuna Islands'),
('WS','Samoa'),
('XK','Kosovo'),
('YE','Yemen'),
('YU','Yugoslavia'),
('ZA','South Africa'),
('ZM','Zambia'),
('ZR','Zaire'),
('ZW','Zimbabwe'),
)

YEARS = (
('1', '1'),
('2', '2'),
('3', '3'),
('4', '4'),
('5', '5'),
('6', '6'),
('7', '7'),
('8', '8'),
('9', '9'),
('10', '10'),
)

dateTimeOptions = {
'format': 'mm/dd/yyyy hh:ii',
'autoclose': True,
'showMeridian' : True,
'daysOfWeekDisabled': [0],
'maxView': 2 
}
HORAS = (
('1', '1 hora'),
('2', '2 horas'),
)

class BuscarDominioForm(forms.Form):
	dominio = forms.CharField(widget=forms.TextInput,max_length=20)
	extension = forms.ChoiceField(choices=SMALL_LIST, required=True, widget=forms.RadioSelect)
	duracion = forms.ChoiceField(choices=YEARS, required=True)

class UserForm(forms.Form):
	tipo = forms.ChoiceField(widget=forms.RadioSelect, choices=TYPE_OF_USERS, required=True)
	usuario = forms.CharField(widget=forms.TextInput, required=True,max_length=30)
	nombres = forms.CharField(widget=forms.TextInput, required=True,max_length=30)
	apellidos = forms.CharField(widget=forms.TextInput, required=True,max_length=30)
	correo = forms.EmailField(max_length=30, required=True)
	password1 = forms.CharField(widget=forms.PasswordInput, label='Password', required=True,max_length=16)
	password2 = forms.CharField(widget=forms.PasswordInput, label='Verifique su password', required=True,max_length=16)
	direccion = forms.CharField(widget=forms.TextInput, required=True,max_length=30)
	zip = forms.CharField(widget=forms.TextInput,max_length=6)
	ciudad = forms.CharField(widget=forms.TextInput, required=True,max_length=30)
	pais = forms.ChoiceField(choices=COUNTRIES, required=True)
	telefono = forms.CharField(widget=forms.TextInput, required=True,max_length=12)

class precioProducto(forms.Form):
	descripcion = forms.CharField(widget=forms.TextInput, required=True,max_length=30)
	tipo = forms.ChoiceField(choices=SERVICES, required=True)
	moneda = forms.ChoiceField(choices=CURRENCY, required=True)
	
class precioDominio(forms.Form):
	duracion = forms.ChoiceField(choices=YEARS, required=True)


class registroAtencion(forms.Form):
	fecha = forms.DateTimeField(widget=DateTimeWidget(options=dateTimeOptions), required=True)
	duracion = forms.ChoiceField(choices=HORAS, required=True)
	titulo = forms.CharField(widget=forms.TextInput, max_length=30, required=True)
	descripcion = forms.CharField(widget=forms.Textarea,required=True)
	
	
